#requires -Version 5.1

[CmdletBinding()]
param(
    [string]$BackupDir,
    [string]$TargetUrl,
    [string]$IdentityFile,
    [string]$TargetLabel,
    [string]$EvidenceFile,
    [switch]$AllowRemote,
    [switch]$AllowDestructive,
    [switch]$Yes
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$scriptDir = $PSScriptRoot
$repoRoot = Split-Path -Parent $scriptDir
$configFile = if ($env:STUDYFLOW_RESTORE_CONFIG) {
    $env:STUDYFLOW_RESTORE_CONFIG
} else {
    Join-Path $scriptDir "restore-config.ps1"
}

if (Test-Path -LiteralPath $configFile -PathType Leaf) {
    . $configFile
}

function Fail([string]$Message) {
    $script:FailureMessage = $Message
    $script:RestoreResult = "fail"
    throw "restore failed: $Message"
}

if ([string]::IsNullOrWhiteSpace($BackupDir)) {
    $BackupDir = if ($env:STUDYFLOW_RESTORE_BACKUP_DIR) { $env:STUDYFLOW_RESTORE_BACKUP_DIR } else { "" }
}
if ([string]::IsNullOrWhiteSpace($TargetUrl)) {
    $TargetUrl = if ($env:STUDYFLOW_RESTORE_DATABASE_URL) { $env:STUDYFLOW_RESTORE_DATABASE_URL } else { "" }
}
if ([string]::IsNullOrWhiteSpace($IdentityFile)) {
    $IdentityFile = if ($env:STUDYFLOW_RESTORE_AGE_IDENTITY_FILE) { $env:STUDYFLOW_RESTORE_AGE_IDENTITY_FILE } else { "" }
}
if ([string]::IsNullOrWhiteSpace($TargetLabel)) {
    $TargetLabel = if ($env:STUDYFLOW_RESTORE_TARGET_LABEL) { $env:STUDYFLOW_RESTORE_TARGET_LABEL } else { "target database (credentials omitted)" }
}
$operator = if ($env:STUDYFLOW_RESTORE_OPERATOR) { $env:STUDYFLOW_RESTORE_OPERATOR } else { $env:USERNAME }
$sourceEnvironment = if ($env:STUDYFLOW_RESTORE_SOURCE_ENVIRONMENT) { $env:STUDYFLOW_RESTORE_SOURCE_ENVIRONMENT } else { "production" }
$sourceProject = if ($env:STUDYFLOW_RESTORE_SOURCE_NEON_PROJECT) { $env:STUDYFLOW_RESTORE_SOURCE_NEON_PROJECT } else { "not recorded" }
$sourceBranch = if ($env:STUDYFLOW_RESTORE_SOURCE_NEON_BRANCH) { $env:STUDYFLOW_RESTORE_SOURCE_NEON_BRANCH } else { "not recorded" }
$drivePath = if ($env:STUDYFLOW_RESTORE_GOOGLE_DRIVE_PATH) { $env:STUDYFLOW_RESTORE_GOOGLE_DRIVE_PATH } else { "not recorded" }
$offlinePath = if ($env:STUDYFLOW_RESTORE_OFFLINE_COPY_PATH) { $env:STUDYFLOW_RESTORE_OFFLINE_COPY_PATH } else { "not recorded" }
$restoreNow = (Get-Date).ToUniversalTime()
$restoreTimestamp = $restoreNow.ToString("yyyyMMddTHHmmssZ")
if ([string]::IsNullOrWhiteSpace($EvidenceFile)) {
    $EvidenceFile = if ($env:STUDYFLOW_RESTORE_EVIDENCE_FILE) { $env:STUDYFLOW_RESTORE_EVIDENCE_FILE } else {
        Join-Path $repoRoot ("docs\evidence\backup-restore-{0}.md" -f $restoreTimestamp)
    }
}

$failureMessage = "none"
$hashResult = "not tested"
$decryptResult = "not tested"
$connectionResult = "not tested"
$restoreResult = "not tested"
$migrationResult = "not tested"
$tableResult = "not tested"
$rowResult = "not tested"
$tableCount = "not recorded"
$postgresVersion = "not recorded"
$migrationVersion = "not recorded"
$rowCounts = "not recorded"
$backupId = "not recorded"
$metadataCreatedAt = "not recorded"
$metadataGitBranch = "not recorded"
$metadataGitCommit = "not recorded"
$metadataGitClean = "not recorded"
$metadataMigration = "not recorded"
$archiveFilename = "not recorded"
$archiveBytes = "not recorded"
$archiveSha256 = "not recorded"
$workDir = $null

function Get-MetadataValue([string]$Path, [string]$Name) {
    $line = Select-String -LiteralPath $Path -Pattern ("^{0}=" -f [regex]::Escape($Name)) | Select-Object -First 1
    if ($null -eq $line) { return "not recorded" }
    return $line.Line.Substring($Name.Length + 1)
}

function Get-SingleFile([string]$Pattern) {
    $files = @(Get-ChildItem -LiteralPath $BackupDir -File -Filter $Pattern)
    if ($files.Count -ne 1) { Fail "expected exactly one $Pattern in $BackupDir; found $($files.Count)" }
    return $files[0].FullName
}

function Write-Evidence {
    $parent = Split-Path -Parent $EvidenceFile
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    @"
# StudyFlow backup and restore evidence

Generated by scripts/restore-backup.ps1.

## Backup record

- Backup identifier: $backupId
- Date and time UTC: $metadataCreatedAt
- Operator: $operator
- Source environment: $sourceEnvironment
- Source Neon project and branch: $sourceProject / $sourceBranch
- Git branch: $metadataGitBranch
- Git commit: $metadataGitCommit
- Git worktree clean: $metadataGitClean
- Migration version in backup metadata: $metadataMigration
- Encrypted archive filename: $archiveFilename
- Encrypted archive size: $archiveBytes bytes
- Encrypted archive SHA-256: $archiveSha256
- Google Drive path: $drivePath
- Offline copy path: $offlinePath

## Restore record

- Restore test date and time UTC: $restoreTimestamp
- Restore operator: $operator
- Restore target: $TargetLabel
- PostgreSQL major version: $postgresVersion
- Encrypted archive checksum: $hashResult
- Archive decryption: $decryptResult
- Restore database connection: $connectionResult
- Restore command completed: $restoreResult
- alembic_version verified: $migrationResult
- Expected tables verified: $tableResult ($tableCount public tables)
- Important row counts verified: $rowResult ($rowCounts)
- Backend readiness verified: not tested
- Login verified: not tested
- Task creation verified: not tested
- Availability verified: not tested
- Schedule generation verified: not tested
- Session outcome recording verified: not tested

## Result

- Overall database restore result: $restoreResult
- Problems found: $failureMessage
- Corrective action: none
- Evidence links or screenshots: terminal output and generated report
"@ | Set-Content -LiteralPath $EvidenceFile -Encoding utf8
}

try {
    if ([string]::IsNullOrWhiteSpace($BackupDir)) { Fail "backup directory is not set" }
    if (-not (Test-Path -LiteralPath $BackupDir -PathType Container)) { Fail "backup directory does not exist: $BackupDir" }
    if ([string]::IsNullOrWhiteSpace($TargetUrl)) { Fail "restore target URL is not set" }
    if ([string]::IsNullOrWhiteSpace($IdentityFile)) { Fail "age identity file is not set" }
    if (-not (Test-Path -LiteralPath $IdentityFile -PathType Leaf)) { Fail "age identity file is not readable: $IdentityFile" }
    if (Test-Path -LiteralPath $EvidenceFile) { Fail "evidence file already exists: $EvidenceFile" }
    if (-not ($TargetUrl.StartsWith("postgresql://") -or $TargetUrl.StartsWith("postgres://"))) {
        Fail "restore target must use postgresql:// or postgres://"
    }
    if ($TargetUrl -like "*-pooler*") { Fail "restore target must use a direct URL, not a -pooler URL" }

    $targetIsLocal = $TargetUrl -match "@(localhost|127\.0\.0\.1|::1|postgres)(:|/)"
    if (-not $targetIsLocal -and -not $AllowRemote) {
        Fail "target is remote; re-run with -AllowRemote after confirming it is not production"
    }
    if ((-not $targetIsLocal -or $AllowDestructive) -and -not $Yes) {
        Fail "re-run with -Yes to confirm the selected target and restore mode"
    }

    $requiredCommands = @("age.exe")
    $commandPaths = @{}
    foreach ($commandName in $requiredCommands) {
        $command = Get-Command $commandName -ErrorAction SilentlyContinue
        if ($null -eq $command) { Fail "required command not found: $commandName" }
        $commandPaths[$commandName] = $command.Source
    }
    $pgRestoreCommand = Get-Command pg_restore.exe -ErrorAction SilentlyContinue
    $psqlCommand = Get-Command psql.exe -ErrorAction SilentlyContinue
    $dockerCommand = Get-Command docker.exe -ErrorAction SilentlyContinue
    if ($null -ne $dockerCommand) { $commandPaths["docker.exe"] = $dockerCommand.Source }
    if ($null -eq $psqlCommand -and $null -eq $dockerCommand) {
        Fail "psql.exe is unavailable and Docker is unavailable for the fallback"
    }
    if ($null -eq $pgRestoreCommand -and $null -eq $dockerCommand) {
        Fail "pg_restore.exe is unavailable and Docker is unavailable for the fallback"
    }

    $encryptedDump = Get-SingleFile "*.dump.age"
    $metadataFile = Get-SingleFile "*.metadata.txt"
    $hashFile = Get-SingleFile "*.sha256"
    $backupId = Get-MetadataValue $metadataFile "backup_id"
    if ($backupId -eq "not recorded") { $backupId = [System.IO.Path]::GetFileNameWithoutExtension([System.IO.Path]::GetFileNameWithoutExtension($encryptedDump)) }
    if ($backupId -notmatch '^[A-Za-z0-9._-]+$') { Fail "backup identifier contains unsupported characters" }
    $metadataCreatedAt = Get-MetadataValue $metadataFile "created_at_utc"
    $metadataGitBranch = Get-MetadataValue $metadataFile "git_branch"
    $metadataGitCommit = Get-MetadataValue $metadataFile "git_commit"
    $metadataGitClean = Get-MetadataValue $metadataFile "git_worktree_clean"
    $metadataMigration = Get-MetadataValue $metadataFile "migration_version"
    $metadataArchiveFilename = Get-MetadataValue $metadataFile "archive_filename"
    $metadataArchiveSha256 = (Get-MetadataValue $metadataFile "archive_sha256").ToLowerInvariant()
    $archiveFilename = Split-Path -Leaf $encryptedDump
    $archiveBytes = (Get-Item -LiteralPath $encryptedDump).Length
    $hashLineValue = Get-Content -LiteralPath $hashFile | Select-Object -First 1
    if ($null -eq $hashLineValue) { Fail "checksum file is empty" }
    $hashParts = $hashLineValue.ToString().Trim() -split '\s+', 2
    if ($hashParts.Count -ne 2) { Fail "checksum file is malformed" }
    $archiveSha256 = $hashParts[0].ToLowerInvariant()
    $hashFilename = $hashParts[1].Trim()
    if ($metadataArchiveFilename -eq "not recorded") { Fail "backup metadata does not record the archive filename" }
    if ($metadataArchiveSha256 -eq "not recorded") { Fail "backup metadata does not record the archive checksum" }
    if ($metadataArchiveFilename -ne $archiveFilename) { Fail "backup metadata does not match the selected archive" }
    if ($hashFilename -ne $archiveFilename) { Fail "checksum file does not match the selected archive" }
    if ($metadataArchiveSha256 -ne $archiveSha256) { Fail "backup metadata does not match the checksum file" }
    $actualHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $encryptedDump).Hash.ToLowerInvariant()
    if ($archiveSha256 -ne $actualHash) { $hashResult = "fail"; Fail "encrypted archive checksum does not match" }
    $hashResult = "pass"

    $workDir = Join-Path ([System.IO.Path]::GetTempPath()) ("studyflow-restore." + [Guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Path $workDir -Force | Out-Null
    $decryptedDump = Join-Path $workDir "$backupId.dump"
    & $commandPaths["age.exe"] --decrypt --identity $IdentityFile --output $decryptedDump $encryptedDump
    if ($LASTEXITCODE -ne 0) { $decryptResult = "fail"; Fail "age could not decrypt the backup" }
    $decryptResult = "pass"

    $composeFile = Join-Path $repoRoot "compose.yaml"
    function Invoke-Psql([string[]]$Arguments) {
        if ($null -ne $psqlCommand) {
            & $psqlCommand.Source --no-psqlrc $TargetUrl @Arguments
        } else {
            & $commandPaths["docker.exe"] compose -f $composeFile exec -T postgres psql --no-psqlrc $TargetUrl @Arguments
        }
        if ($LASTEXITCODE -ne 0) { throw "psql query failed" }
    }
    function Get-PsqlValue([string]$Sql) {
        $output = @(Invoke-Psql @("--tuples-only", "--no-align", "--command=$Sql"))
        return (($output | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -First 1).Trim())
    }

    try {
        $null = Get-PsqlValue "SELECT current_database();"
        $connectionResult = "pass"
    } catch {
        $connectionResult = "fail"
        Fail "could not connect to restore target"
    }
    $postgresVersion = Get-PsqlValue "SHOW server_version;"

    $restoreArgs = @("--dbname=$TargetUrl", "--no-owner", "--no-acl", "--exit-on-error")
    if ($AllowDestructive) { $restoreArgs += @("--clean", "--if-exists") }
    if ($null -ne $pgRestoreCommand) {
        & $pgRestoreCommand.Source @restoreArgs $decryptedDump
        if ($LASTEXITCODE -ne 0) { $restoreResult = "fail"; Fail "pg_restore failed" }
    } else {
        $containerId = (& $commandPaths["docker.exe"] compose -f $composeFile ps -q postgres 2>$null | Select-Object -First 1).Trim()
        if ([string]::IsNullOrWhiteSpace($containerId)) { Fail "pg_restore is unavailable; start the Docker Compose postgres service first" }
        $containerDump = "/tmp/studyflow-restore-$backupId.dump"
        & $commandPaths["docker.exe"] cp $decryptedDump "${containerId}:$containerDump"
        if ($LASTEXITCODE -ne 0) { Fail "could not copy dump into the Docker container" }
        try {
            & $commandPaths["docker.exe"] compose -f $composeFile exec -T postgres pg_restore @restoreArgs $containerDump
            if ($LASTEXITCODE -ne 0) { $restoreResult = "fail"; Fail "Docker pg_restore failed" }
        } finally {
            & $commandPaths["docker.exe"] compose -f $composeFile exec -T postgres rm -f $containerDump 2>$null | Out-Null
        }
    }
    $restoreResult = "pass"

    $expectedTables = @(
        "academic_tasks", "alembic_version", "authentication_account_deletion_challenges", "authentication_email_tokens", "authentication_identities",
        "authentication_oidc_link_challenges", "authentication_oidc_states", "authentication_rate_limits",
        "authentication_registrations", "authentication_sessions", "availability_windows",
        "proposal_task_allocations", "recovery_snapshot_outcomes", "recovery_task_work", "schedule_proposals",
        "schedule_recovery_snapshots", "student_accounts", "study_session_outcomes", "study_sessions",
        "task_deadline_history", "unavailable_periods"
    )
    $missingTables = @()
    foreach ($table in $expectedTables) {
        if ((Get-PsqlValue "SELECT to_regclass('public.$table') IS NOT NULL;") -ne "t") { $missingTables += $table }
    }
    $tableCount = Get-PsqlValue "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE';"
    if ($missingTables.Count -gt 0) { $tableResult = "fail"; Fail "missing expected tables: $($missingTables -join ', ')" }
    $tableResult = "pass"

    $migrationVersion = Get-PsqlValue "SELECT version_num FROM alembic_version LIMIT 1;"
    if ([string]::IsNullOrWhiteSpace($migrationVersion)) { $migrationResult = "fail"; Fail "alembic_version did not contain a migration version" }
    $migrationResult = "pass"

    $importantTables = @("student_accounts", "academic_tasks", "availability_windows", "study_sessions")
    $rowCountValues = @()
    foreach ($table in $importantTables) {
        $rowCountValues += "$table=$(Get-PsqlValue "SELECT count(*) FROM public.$table;")"
    }
    $rowCounts = $rowCountValues -join " "
    $rowResult = "pass"
    $restoreResult = "pass"
} catch {
    if ($failureMessage -eq "none") { $failureMessage = $_.Exception.Message }
    throw
} finally {
    if ($null -ne $workDir -and (Test-Path -LiteralPath $workDir)) {
        Remove-Item -LiteralPath $workDir -Recurse -Force
    }
    try {
        Write-Evidence
    } catch {
        if ($restoreResult -eq "pass") {
            $restoreResult = "fail"
            $failureMessage = "could not write evidence file: $($_.Exception.Message)"
            throw
        }
        Write-Warning "could not write evidence file: $($_.Exception.Message)"
    }
}

Write-Host "Restore complete. Evidence written to $EvidenceFile"
